language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- ls Assets/CoinFlipGames/Sleepy/Scripts/install.sh
install:
- ./Assets/CoinFlipGames/Sleepy/Scripts/install.sh
script:
- ./Assets/CoinFlipGames/Sleepy/Scripts/build.sh
